# Site
name: "Duke Institute for Brain Sciences Methods Meetings"
title: "Duke Institute for Brain Sciences Methods Meetings"
description: "Workshops and tutorials on  methods, statistics, and models in neuroscience."
logo: 'assets/images/logo.jpg'
favicon: 'assets/images/logo.jpg'
baseurl: 
include: ["_pages"]
permalink: /:title/
future: true

# Authors
authors:
  allie:
    name: Allie
    display_name: Allie Sinclair
    avatar: assets/images/Sinclair.jpeg
    gravatar:
    email: asinclair@rice.edu
    web: https://alyssasinclair.com
    twitter: https://twitter.com/sinclair_allie
    description: "Assistant Professor at Rice University studying how people update their memories, beliefs, and behaviors. Former PhD Candidate in Cognitive Neuroscience at Duke University working with Dr. Alison Adcock and Dr. Gregory Samanez-Larkin studying how people learn from error."

  anne:
    name: Anne
    display_name: Anne Draelos
    avatar: assets/images/anne.jpg
    gravatar:
    email: adraelos@umich.edu
    web: https://draelos.github.io
    twitter: https://twitter.com/annedraelos
    description: "Assistant Professor at the University of Michigan applying machine learning and statistical techniques to facilitate real-time analysis of neural and behavioral data. Former postdoc at Duke University working with Dr. John Pearson developing a real-time neural analysis platform."

  ari:
    name: Ari
    display_name: Ari Khoudary
    avatar: assets/images/ari.jpeg
    gravatar:
    email: ari.khoudary@uci.edu
    web: https://arikhoudary.com
    twitter: https://twitter.com/ari_khoudary
    description: "PhD student in Cognitive Science at UC Irvine working with Drs. Megan Peters and Aaron Bornstein to study how humans use past experiences to behave more adaptively in the present."

  audrey:
    name: Audrey
    display_name: Audrey Siqi-Liu
    avatar: assets/images/audrey.png
    gravatar:
    email: audrey.liu@gwu.edu
    web: https://sites.google.com/view/audreysiqiliu
    twitter: 
    description: "Postdoc at George Washington University working with Drs. Stephen Mitroff and Dwight Kravits on questions about visual cognition. Former PhD student at Duke University working with Drs. Tobias Egner and Marty Woldorff to study adaptive cognitive flexibility."

  breanna:
    name: Breanna
    display_name: Breanna Nguyen
    avatar: assets/images/breanna.jpg
    gravatar:
    email: breanna.nguyen@duke.edu
    web: https://breannaknguyen.github.io/
    twitter: 
    description: "Post-baccalaureate researcher at Duke University working with Dr. Walter Sinnott-Armstrong on computational cognition, the natural environment and mental health, experimental philosophy, and modeling moral decisions."

  clara:
    name: Clara
    display_name: Clara Sandu
    avatar: assets/images/clara.png
    gravatar:
    email: clara.sandu@duke.edu
    web: 
    twitter: 
    description: "Lab manager and research associate at Duke University working with Dr. Scott Huettel on the cognitive underpinnings of complex social behavior and decision-making, including processes such as empathy/theory of mind, sensory perception, attention, memory, and imagination."

  daniela:
    name: Daniela
    display_name: Daniela DeAlbuquerque
    avatar: assets/images/daniela.jpg
    gravatar:
    email: dfd4@duke.edu
    web: 
    twitter: 
    description: "MD-PhD Student in Electrical and Computer Engineering at Duke University working with Dr. John Pearson to apply modern machine learning and data science techniques to develop new methods for brain imaging analysis."

  deborah:
    name: Deborah
    display_name: Deborah Cesarini
    avatar: assets/images/deborah.jpg
    gravatar:
    email: deborah.cesarini@duke.edu
    web:
    twitter:
    description: "Coordinator of DIBS Methods Meetings. PhD student at Duke University working with Drs. Walter Sinnott-Armstrong and Scott Huettel on how real and fictional narratives influence people's moral cognition, with a focus on developing interventions to enhance moral decision-making."

  ding:
    name: Ding
    display_name: Yaohui Ding
    avatar: assets/images/ding.png
    gravatar:
    email: yd169@duke.edu
    web:
    twitter:
    description: "Postdoctoral associate at Duke University working with Dr. Kevin LaBar on neural computational modeling of affect and emotion, brain connectivity, and psychophysiology."

  gabriela:
    name: Gabriela
    display_name: Gabriela Fernandez Miranda
    avatar: assets/images/gabriela.jpg
    gravatar:
    email: gabriela.fernandez@duke.edu
    web: https://gabrielafernandezmiranda.github.io
    twitter: https://twitter.com/GabrielaFM12
    description: "PhD Student at Duke University working with Dr. Felipe De Brigard to understand the effect that forgiveness has on traumatic memories in the context of war."

  helen:
    name: Helen
    display_name: Helen Vonderhaar
    avatar: assets/images/helen.jpg
    gravatar:
    email: helen.vonderhaar@duke.edu
    web:
    twitter:
    description: "Lab manager and research associate at Duke University working with Dr. Rick Hoyle in the Center for the Study of Addictive Risk and Resilience."

  ilayda:
    name: Ilayda
    display_name: Ilayda Orhan
    avatar: assets/images/ilayda.jpg
    gravatar:
    email: ilayda.orhan@duke.edu
    web:
    twitter:
    description: "PhD student at Duke University working with Dr. Maureen Craig on how people conceptualize different social inequalities and what leads them to act in ways that either mitigate, maintain or exacerbate these inequalities."

  jade:
    name: Jade
    display_name: Jade Terry
    avatar: assets/images/jade.png
    gravatar:
    email: jade.terry@duke.edu
    web:
    twitter:
    description: "PhD student at Duke University working with Drs. Scott Huettel and Greg Samanez-Larkin on the influence of social inequalities and social status in decision making."

  jim:
    name: Jim
    display_name: Jim Zhang
    avatar: assets/images/jim.jpg
    gravatar:
    email: jim.zhang@duke.edu
    web:
    twitter:
    description: "PhD student at Duke University working with Dr. Tobias Egner on how subjective experiences arise from neural activity, the application of stimulation (TMS) to improve semantic memory in MCI adults, and the influence of episodic memory on cognitive control levels."

  jaime:
    name: Jaime
    display_name: Jaime Rios
    avatar: assets/images/jaime.png
    gravatar:
    email: jaime.rios@duke.edu
    web:
    twitter:
    description: "PhD student at Duke University working with Dr. Tobias Egner on \"Sequential Control\" or the dynamic trial to trial changes that take place throughout control-based behavior"

  kaylee:
    name: Kaylee
    display_name: Kaylee Miceli
    avatar: assets/images/kaylee.jpg
    gravatar:
    email: kaylee.miceli@duke.edu
    web: 
    twitter: https://x.com/miceli_k
    description: "PhD student at Duke University working with Drs. Cristina Salvador and Felipe De Brigard on how memory and self differ across cultures with varying levels of interdependence."

  ken:
    name: Ken
    display_name: Ken Roberts
    avatar: assets/images/ken.jpg
    gravatar:
    email: ken.roberts@duke.edu
    web:
    twitter:
    description: "Lab manager at Duke University working with Dr. Marty Woldorff to apply emerging methodological techniques to investigate the neural basis of cognitive processes."

  kevin:
    name: Kevin
    display_name: Kevin O'Neill
    avatar: assets/images/kevin.jpg
    gravatar:
    email: kevin.oneill@duke.edu
    web: https://kevingoneill.github.io
    twitter:
    description: "Postdoc at University College London working on metacognition and causal reasoning. Former PhD student at Duke University with Drs. Felipe De Brigard and John Pearson. Founder of DIBS Methods Meetings."

  liz:
    name: Liz
    display_name: Liz O'Gorman
    avatar: assets/images/liz.png
    gravatar:
    email: elizabeth.ogorman@duke.edu
    web: https://eaogorman.github.io/
    twitter: https://twitter.com/eaogorman
    description: "Former PhD student at Duke University working with Dr. John Pearson on real-time adaptive experimental methods and deep learning."

  lucas:
    name: Lucas
    display_name: Lucas Bellaiche
    avatar: assets/images/lucas.jpg
    gravatar:
    email: lucas.bellaiche@duke.edu
    web: https://sites.google.com/view/lucasbellaiche
    twitter:
    description: "PhD student at Duke University working with Dr. Kevin LaBar on interdisciplinary research avenues at the intersection of creativity and emotion."

  miles:
    name: Miles
    display_name: Miles Martinez
    avatar: assets/images/miles.jpg
    gravatar:
    email: miles.martinez@duke.edu
    web:
    twitter:
    description: "PhD Student at Duke University working with Dr. John Pearson to develop and apply computational methods to understand the neural bases of natural learning."

  nathan:
    name: Nathan
    display_name: Nathan Liang
    avatar: assets/images/nathan.jpg
    gravatar:
    email: nl453@cornell.edu
    web: https://1nathanliang.github.io
    twitter: https://twitter.com/1nathan_liang
    description: "PhD Student in Social & Personality Psychology at Cornell University working with Dr. Laura Niemi on social learning and moral reasoning."

  pranjal:
    name: Pranjal
    display_name: Pranjal Gupta
    avatar: assets/images/pranjal.jpg
    gravatar:
    email: pranjal.gupta@duke.edu
    web:
    twitter:
    description: "Data scientist. Former PhD Student at Duke University working with Dr. John Pearson on online dimensionality reduction."

  raphael:
    name: Raphael
    display_name: Raphael Geddert
    avatar: assets/images/raphael.jpg
    gravatar:
    email: raphael.geddert@duke.edu
    web:
    twitter: https://twitter.com/raphaelgeddert
    description: "Senior Associate Data Scientist at Gilead Sciences. Former PhD student at Duke University working with Dr. Tobias Egner on cognitive control."

  shenyang:
    name: Shenyang
    display_name: Shenyang Huang
    avatar: assets/images/shenyang.jpg
    gravatar:
    email: shenyang.huang@duke.edu
    web: https://huang-shenyang.github.io/
    twitter: https://twitter.com/SelfShenyang
    description: "Applied Scientist at Microsoft AI working on improving peopleâ€™s search experiences with Bing. Former PhD student at Duke University working with Drs. Roberto Cabeza, Simon Davis, and Felipe De Brigard on the behavioral and neural attributes of human memory."

  trevor:
    name: Trevor
    display_name: Trevor Alston
    avatar: assets/images/trevor.jpg
    gravatar:
    email: trevor.alston@duke.edu
    web:
    twitter:
    description: "PhD Student at Duke University working with Dr. John Pearson to build a real-time tool for detecting latent patterns for oscillatory neural data."

  xinhao:
    name: Xinhao
    display_name: Xinhao Wang
    avatar: assets/images/xinhao.jpeg
    gravatar:
    email: xinhao.wang@duke.edu
    web:
    twitter:
    description: "PhD student at Duke University working with Dr. Roberto Cabeza on verbal insights using functional magnetic resonance imaging data, hoping to investigate the role of hippocampus and its associated networks."

collections:
  personal_page:
    output: true

defaults:
  - scope:
      path: ""
      type: personal_page
    values:
      layout: personal_page
      permalink: people/:name

google_site_verification : google5d59576ff62047c3.html

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
#markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client:
adsense-data-ad-slot:

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock, cache, _source, render]

theme: jekyll-theme-minimal
